price1 = float(input("ราคาสินค้า1 "))
amount1 = int(input("จำนวนสินค้า1 "))
price2 = float(input("ราคาสินค้า2 "))
amount2 = int(input("จำนวนสินค้า2 "))
total = (price1 * amount2 ) + (price2 * amount2 )
print("ค่าใช้จ่ายของคุณครั้งนี้ \nคือ ", total, "บาท")